### ISSUE TITLE
yaml.load in vresutils.snakemake.MockSnakemake returns warning

### ISSUE THREAD

**Issue by neunzehnachtneun** [FRESNA/vresutils#12]
When using MockSnakemake I get the following error:
```
YAMLLoadWarning: calling yaml.load() without Loader=... 
is deprecated, as the default Loader is unsafe. Please read 
https://msg.pyyaml.org/load for full details.
  self.config = yaml.load(f)
```

As written in the PyYAML doc, there has been filed a CVE against the module. So I would suggest to change line 38 in vresutils.snakemake from `self.config = yaml.load(f)` to `self.config = yaml.save_load(f)`.

**Comment by coroa** [comment]
Yes, that's the correct fix! ~Feel free to prepare a PR!~

Note also that the vresutils.MockSnakemake module is getting replaced in favour of
https://github.com/PyPSA/pypsa-eur/commit/eaf30a9b6552a9cc1b53d5ef94d677553656d854#diff-3534ab6f36e6081bdd1919c2bfccea79R156
